translate start-a-new-project
reactjs/it.react.dev pull request #419
Opened 2023-04-25 10:09 UTC by webdiego

Added italian translation for a start-a-new-project.md and I also translated the index in installation.md

Ps: my first contribution :)

2023-04-25 19:45 UTC, mattia-sanfilippo requested changes
Ciao @webdiego, grazie!! 🚀 
Ho aggiunto qualche commento per correggere alcune frasi.

Fammi sapere cosa ne pensi!

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +**[Remix](https://remix.run/) è un framework React a stack completo con routing nidificato.** Ti consente di suddividere la tua app in parti nidificate che possono caricare dati in parallelo e aggior
```suggestion
**[Remix](https://remix.run/) è un framework React full-stack con routing nidificato.** Ti consente di suddividere la tua app in parti nidificate che possono caricare dati in parallelo e aggiornarsi in risposta alle azioni dell'utente. Per creare un nuovo progetto Remix, esegui il seguente comando:
```
Manterrei il termine "full-stack" anche qui, per consistenza, come fatto poco sopra. Cosa ne pensi? 🙂

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/)  un framework per React che ti consente di creare app universali per Android, iOS e web con interfacce utente veramente native.** Fornisce un SDK per [React Native](https:
```suggestion
**[Expo](https://expo.dev/) è un framework per React che ti consente di creare app universali per Android, iOS e web con interfacce utente veramente native.** Fornisce un SDK per [React Native](https://reactnative.dev/) che semplifica l'utilizzo delle parti native. Per creare un nuovo progetto Expo, esegui il seguente comando:
```

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +Expo è mantenuto da [Expo ('l'azienda)](https://expo.dev/about). La creazione di app con Expo è gratuita e puoi inviarle ai negozi di app di Google e Apple senza restrizioni. Expo fornisce inoltre se
```suggestion
Expo è mantenuto da [Expo (l'azienda)](https://expo.dev/about). La creazione di app con Expo è gratuita e puoi inviarle ai negozi di app di Google e Apple senza restrizioni. Expo fornisce inoltre servizi cloud a pagamento opzionali.
```

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +Expo è mantenuto da [Expo ('l'azienda)](https://expo.dev/about). La creazione di app con Expo è gratuita e puoi inviarle ai negozi di app di Google e Apple senza restrizioni. Expo fornisce inoltre se
```suggestion
Expo è mantenuto da [Expo ('l'azienda)](https://expo.dev/about). La creazione di app con Expo è gratuita e puoi inviarle agli app store di Google e Apple senza restrizioni. Expo fornisce inoltre servizi cloud a pagamento opzionali.
```

Terrei il termine "app store" non tradotto, in quanto di utilizzo comune nella lingua italiana. Cosa ne pensi?

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +**I framework React presenti in questa pagina risolvono questi problemi di default, senza alcun lavoro aggiuntivo da parte tua.** Ti permettono di iniziare con una configurazione leggera e poi scalar
```suggestion
**I framework React presenti in questa pagina risolvono questi problemi di default, senza alcun lavoro aggiuntivo da parte tua.** Ti permettono di iniziare con una configurazione leggera e poi scalare la tua app in base alle tue esigenze. Ogni framework React ha una comunità, quindi trovare risposte alle domande e aggiornare gli strumenti è più facile. Inoltre, i framework forniscono una struttura al tuo codice, aiutando te stesso e gli altri a mantenere il contesto e le competenze tra diversi progetti. Al contrario, con una configurazione personalizzata è più facile rimanere bloccati con versioni di dipendenze non supportate, e alla fine finirai per creare il tuo framework, anche se in modo meno strutturato e senza una comunità o un percorso di aggiornamento (e se è simile a quelli che abbiamo creato in passato, potrebbe essere progettato in modo più casuale).
```

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +Il router dell'app di Next.js è **attualmente in fase beta e non è ancora consigliato per la produzione** (al marzo 2023). Per sperimentarlo in un progetto Next.js esistente,  [segui questa guida di
```suggestion
Il router dell'app di Next.js è **attualmente in fase beta e non è ancora consigliato per la produzione** (al marzo 2023). Per sperimentarlo in un progetto Next.js esistente, [segui questa guida di migrazione incrementale.](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app).
```

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +Il router dell'app di Next.js integra anche il [recupero dei dati con Suspense.](/blog/2022/03/29/react-v18#suspense-in-data-frameworks).Questo consente di specificare uno stato di caricamento (come
```suggestion
Il router dell'app di Next.js integra anche il [recupero dei dati con Suspense.](/blog/2022/03/29/react-v18#suspense-in-data-frameworks). Questo consente di specificare uno stato di caricamento (come un segnaposto scheletro) per diverse parti dell'interfaccia utente direttamente nell'albero di React:
```

2023-04-25 19:45 UTC, mattia-sanfilippo commented on src/content/learn/start-a-new-react-project.md
> +Server Components e Suspense sono funzionalità di React che possono essere adottate a livello di framework. Al momento, il Next.js App Router è l'implementazione più completa di queste funzionalità t
Per consistenza terrei solo una versione di `Next.js App Router`, nelle righe sopra viene tradotto come `router dell'app di Next.js`. 
Cosa ne pensi? 💪🏻

2023-04-25 21:33 UTC, webdiego commented on src/content/learn/start-a-new-react-project.md
> +Server Components e Suspense sono funzionalità di React che possono essere adottate a livello di framework. Al momento, il Next.js App Router è l'implementazione più completa di queste funzionalità t
Si sono d'accordo! Grazie per la review :)

2023-04-26 10:03 UTC, deblasis requested changes

2023-04-26 10:03 UTC, deblasis commented on src/content/learn/start-a-new-react-project.md
> +title: Avviare un nuovo progetto React
Ciao @webdiego ! 
Ottimo lavoro ❤️

Solo un suggerimento ed una piccola aggiunta se mi posso azzardare :)

```suggestion
title: Avviare un Nuovo Progetto React
```
per consistenza con lo stile del team React (i titoli delle pagine sono "maiuscolati")

inoltre, ti dispiace aggiornare anche `sidebarLearn.json` ?

![image](https://user-images.githubusercontent.com/29378614/234542146-ea0db1b9-d15a-4619-a945-82757e4a1985.png)

2023-04-26 10:27 UTC, webdiego commented on src/content/learn/start-a-new-react-project.md
> +title: Avviare un nuovo progetto React
Grazie @deblasis,ho apportato le modifiche richieste, perdonami ma è la mia prima contributions ed è tutto nuovo per me! Grazie mille :)

2023-04-26 12:06 UTC, deblasis approved these changes
🚀  LGTM

2023-04-26 12:08 UTC, merged

2023-04-26 12:23 UTC, webdiego commented
Graziee! Super felice della mia prima contribution! :) :) @mattia-sanfilippo @mattia-sanfilippo