Thinking in react translation
reactjs/it.react.dev pull request #421
Opened 2023-04-25 14:43 UTC by SamuelePiazzesi

Added translations for `thinking-in-react` section.

2023-04-25 20:39 UTC, mattia-sanfilippo requested changes
Ciao @SamuelePiazzesi 👋 
Grazie per l'aiuto!! 🚀 

Ho lasciato qualche commento. Fammi sapere cosa ne pensi :)

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +* Viene **passato da un componente genitore** via props? Allora non è state.
```suggestion
* Viene **passato da un componente genitore** tramite props? Allora non è state.
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +* **Puoi calcolarlo** basandoti su uno state diverso o da props nel tuo componente? Allora **sicuramente non é** state!
```suggestion
* **Puoi calcolarlo** basandoti su uno state diverso o da props nel tuo componente? Allora **sicuramente** non è state!
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +Quello che è rimane probabilmente può considerarsi state.
```suggestion
Quello che è rimasto probabilmente può considerarsi state.
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +1. la lista originale di prodotti è **passata in via props, quindi non è state.**
```suggestion
1. La lista originale di prodotti è **passata tramite props, quindi non è state.**
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +Aggiungi lo state al componente con l'[`useState()` Hook.](/reference/react/useState) Gli Hooks sono funzioni speciali che ti permettono di "collegarti" a React. Aggiungi due variabili state all'iniz
```suggestion
Aggiungi lo state al componente con l'[Hook `useState()`.](/reference/react/useState) Gli Hooks sono funzioni speciali che ti permettono di "collegarti" a React. Aggiungi due variabili state all'inizio di `FilterableProductTable` e specifica il loro stato iniziale:
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +Puoi iniziare a vedere come si comporterà la tua applicazione. Modifica il valore iniziale di `filterText` da `useState('')` a `useState('fruit')` nel codice sandbox qui sotto. Vedrai sia il testo di
```suggestion
Puoi iniziare a vedere come si comporterà la tua applicazione. Modifica il valore iniziale di `filterText` da `useState('')` a `useState('fruit')` nel codice sandbox qui sotto. Vedrai che sia il testo di input di ricerca che la tabella si aggiornano:
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +Nota che la modifica del form non funziona ancora. Nello sandbox sopra c'è un errore di console che spiega perché:
```suggestion
Nota che la modifica del form non funziona ancora. Nel sandbox sopra c'è un errore di console che spiega perché:
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +Nel sandbox sopra, `ProductTable` e `SearchBar` leggono le props `filterText` e `inStockOnly` per renderizzare la tabella, l'input e checkbox. Ad esempio, ecco come `SearchBar` popola il valore dell'
```suggestion
Nel sandbox sopra, `ProductTable` e `SearchBar` leggono le props `filterText` e `inStockOnly` per renderizzare la tabella, l'input e la checkbox. Ad esempio, ecco come `SearchBar` popola il valore dell'input:
```

2023-04-25 20:39 UTC, mattia-sanfilippo commented on src/content/learn/thinking-in-react.md
> +React rende questo flusso di dati in modo esplicito, ma richiede un po' più di scrittura rispetto al two-way data binding. Se provi a digitare o a spuntare la checkbox nell'esempio qui sopra, vedrai
```suggestion
React rende questo flusso di dati in modo esplicito, ma richiede un po' più di scrittura rispetto al two-way data binding. Se provi a digitare o a spuntare la checkbox nell'esempio qui sopra, vedrai che React ignora il tuo input. Questo è voluto. Scrivendo `<input value={filterText} />`, hai impostato la prop `value` dell'`input` per essere sempre uguale allo stato `filterText` passato da `FilterableProductTable`. Poiché lo stato `filterText` non viene mai impostato, l'input non cambia mai.
```

2023-04-26 06:48 UTC, SamuelePiazzesi commented on src/content/learn/thinking-in-react.md
> +* **Programming**--usa la stesso metodo per decidere se creare una nuova funzione o un nuovo oggetto. Uno di questi metodi è la [single responsibility principle](https://en.wikipedia.org/wiki/Single_
Assolutamente si! Grazie

2023-04-26 06:56 UTC, SamuelePiazzesi commented
Ciao @mattia-sanfilippo :D!
Per me è un piacere dare una mano!
Ho visto tutti i tuoi commenti e secondo me sono tutti da committare, grazie per il tuo secondo parere!

2023-04-26 10:07 UTC, deblasis commented on src/content/learn/thinking-in-react.md
> +
```suggestion
```
rimozione extra \n

2023-04-26 10:07 UTC, deblasis commented on src/content/learn/thinking-in-react.md
>  Now the application fully works!
```suggestion
```

2023-04-26 10:18 UTC, deblasis requested changes
Ottimo lavoro @SamuelePiazzesi !

Ho lasciato un paio di commenti ed ho aggiornato i riferimenti alla pagina.

Facci sapere cosa ne pensi

2023-04-26 11:31 UTC, SamuelePiazzesi commented
Ciao @deblasis!

Grazie mille per le correzioni, mi sembrano ottime!

2023-04-26 12:11 UTC, mattia-sanfilippo approved these changes

2023-04-26 12:16 UTC, deblasis approved these changes

2023-04-26 12:16 UTC, merged