JavaScript in JSX with Curly Braces translation
reactjs/it.react.dev pull request #426
Opened 2023-04-27 10:28 UTC by SamuelePiazzesi

JavaScript in JSX with Curly Braces translation

2023-04-27 16:09 UTC, deblasis commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +title: JavaScript in JSX con le parentesi graffe
```suggestion
title: JavaScript in JSX con le Parentesi Graffe
```
per consistenza con lo stile dei titoli seguito del team React 

Bonus: Ti dispiacerebbe anche aggiornare la sidebar con la stessa traduzione ed eventuali riferimenti a questa pagina? 😉
Se cerchi "JavaScript in JSX with Curly Braces" all'interno del codice capirai cosa intendo.

2023-04-27 16:11 UTC, deblasis commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Nota la differenza tra `className="avatar"`, che specifica un nome di classe CSS `"avatar"` che rende l'immagine rotonda, e `src={avatar}` che legge il valore della variabile JavaScript chiamata `ava
```suggestion
Nota la differenza tra `className="avatar"`, che specifica un nome di classe CSS `"avatar"` che rende l'immagine rotonda, e `src={avatar}` che legge il valore della variabile JavaScript chiamata `avatar`. Questo perché le parentesi graffe ti permettono di lavorare con JavaScript proprio lì nel tuo markup!
```
spazio

2023-04-27 16:15 UTC, deblasis commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Questo codice crasha con un errore che dice `Objects are not valid as a React child`:
```suggestion
Questo codice _crasha_ con un errore che dice `Objects are not valid as a React child`:
```
O tra virgolette, cosa ne pensi?

2023-04-27 16:18 UTC, deblasis requested changes
Ottimo lavoro @SamuelePiazzesi! Un paio di _mini-minuzie_ ma è praticamente perfetta

2023-04-28 07:06 UTC, SamuelePiazzesi commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +title: JavaScript in JSX con le parentesi graffe
Ciao @deblasis , grazie mille! Ho aggiornato anche il titolo della sidebar!

2023-04-28 07:40 UTC, deblasis approved these changes
👏

2023-04-28 07:40 UTC, merged