Translated Describing the UI
reactjs/it.react.dev pull request #427
Opened 2023-04-27 22:35 UTC by Ago95Dev

Italian translation for "Describing the UI" page and sidebar entry.

Part of https://github.com/reactjs/it.react.dev/issues/418

2023-04-27 23:56 UTC, Th3Wall requested changes

2023-04-27 23:56 UTC, Th3Wall commented on src/sidebarLearn.json
> +      "title": "Descrivere l'UI",
```suggestion
      "title": "Descrivere la UI",
```

2023-04-28 07:51 UTC, deblasis commented on src/sidebarLearn.json
> +      "title": "Descrivere l'UI",
Se cambiamo qui, direi che anche il titolo della pagina 

https://github.com/reactjs/it.react.dev/pull/427/files#diff-a528d08fdde7a2c9ff6b846ad27d186ac2c658ab6163385622c110e6f1b5ffc3R2

e altri riferimenti tipo: 

https://github.com/reactjs/it.react.dev/pull/427/files#diff-a528d08fdde7a2c9ff6b846ad27d186ac2c658ab6163385622c110e6f1b5ffc3R7

andrebbero aggiornati.

Non ho personalmente una forte preferenza tra `l'UI` e `la UI` (colloquialmente credo di aver usato entrambe le forme ma non parlo "tech" in Italiano da anni). A prescindere, mi piacerebbe un approccio consistente.

Che ne pensate @Ago95Dev e @Th3Wall ?

2023-04-28 08:20 UTC, Th3Wall commented on src/sidebarLearn.json
> +      "title": "Descrivere l'UI",
Assolutamente, concordo con te @deblasis 😃 
Anche a me non capita di parlare "tech" in Italiano ed è effettivamente un po' _weird_ 😅
IMO `la UI` risulta più "fluido" nella lettura piuttosto che `l'UI`

2023-04-28 09:17 UTC, deblasis commented on src/sidebarLearn.json
> +      "title": "Descrivere l'UI",
Nice!

Teamwork = Dreamwork

😄

2023-04-28 09:34 UTC, deblasis approved these changes
Ottimo lavoro 👍

Mi sono permesso di aggiornare i riferimenti ai titoli con le maiuscole

2023-04-28 09:46 UTC, merged