Translated page content && Expandable Collout
reactjs/it.react.dev pull request #431
Opened 2023-04-29 21:07 UTC by Th3Wall

Translation for _"Conditional Rendering"_ page.
Also added <ExpandableCollout> and <ExpandableExample> components translations.

Ref https://github.com/reactjs/it.react.dev/issues/418

2023-05-05 20:04 UTC, mattia-sanfilippo requested changes
Ciao @Th3Wall, grazie e ottimo lavoro!! 🚀 
Ho lasciato qualche piccolo commento ma nulla di che, facci sapere cosa ne pensi :)

2023-05-05 20:04 UTC, mattia-sanfilippo commented on src/content/learn/conditional-rendering.md
> +Puoi scrivere questo come un [`if`/`else` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else) in questo modo:
```suggestion
Puoi scrivere questo come un'[istruzione `if`/`else`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else) in questo modo:
```
ho visto che nelle altre righe hai usato `istruzione`, lo tradurrei così anche qui 🙂 cosa ne pensi?

2023-05-08 23:06 UTC, Th3Wall commented on src/content/learn/conditional-rendering.md
> +Puoi scrivere questo come un [`if`/`else` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else) in questo modo:
My bad! Grazie per la segnalazione 😉

2023-05-08 23:07 UTC, Th3Wall reviewed
Suggested changes applied

2023-05-28 14:55 UTC, deblasis approved these changes
🚀

2023-05-28 14:56 UTC, merged