Translate: State A Component's Memory
reactjs/it.react.dev pull request #439
Opened 2023-05-02 22:50 UTC by oxcened

Partially addresses https://github.com/reactjs/it.react.dev/issues/418.

- Translation of page content.
- Translation of page title in `sidebarLearn.json`.

2023-05-28 15:47 UTC, mattia-sanfilippo requested changes
Ciao @oxcened, grazie mille per aver contribuito 😄 
Ho suggerito alcune piccolissime modifiche, fammi sapere cosa ne pensi! 🚀

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +2. **Triggerare** React per renderizzare il componente con nuovi dati (re-renderizzazione).
```suggestion
2. **Triggerare** React per renderizzare il componente con nuovi dati (ri-renderizzazione).
```

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +**Gli Hook (funzioni che iniziano per `use`) possono essere chiamati solo al livello superiore del tuo componente o [dei tuoi Hook.](/learn/reusing-logic-with-custom-hooks)** Non è possibile chiamare
```suggestion
**Gli Hook (funzioni che iniziano per `use`) possono essere chiamati solo al livello superiore del tuo componente o [dei tuoi Hook.](/learn/reusing-logic-with-custom-hooks)** Non è possibile chiamare gli Hook all'interno di condizioni, cicli o altre funzioni nidificate. Gli Hook sono funzioni, ma è di aiuto considerarli come dichiarazioni incondizionate sulle necessità del tuo componente. "Usi" le funzionalità di React in cima al tuo componente in modo simile a come "importi" i moduli in cima al tuo file. 
```

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +Avrai notato che la chiamata `useState` non riceve alcuna informazione circa *quale* variabile di stato prendere come riferimento. Non viene passato alcun "identificatore" a `useState`, quindi come f
```suggestion
Avrai notato che la chiamata `useState` non riceve alcuna informazione circa *quale* variabile di state prendere come riferimento. Non viene passato alcun "identificatore" a `useState`, quindi come fa a sapere quale delle variabili di state restituire? Fa affidamento su qualche magia come il parsing delle tue funzioni? La risposta è no.
```
Teniamo `state` :)

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +Internamente, React mantiene un array di coppie di stato per ogni componente. Mantiene anche l'indice della coppia corrente, che viene impostato su `0` prima della renderizzazione. Ogni volta che chi
```suggestion
Internamente, React mantiene un array di coppie di state per ogni componente. Mantiene anche l'indice della coppia corrente, che viene impostato su `0` prima della renderizzazione. Ogni volta che chiami `useState`, React ti fornisce la coppia di state successiva e incrementa l'indice. Puoi leggere di più su questo meccanismo in [React Hooks: Not Magic, Just Arrays.](https://medium.com/@ryardley/react-hooks-not-magic-just-arrays-cd4f1857236e)
```
Terrei il titolo di quella pagina web in inglese, visto che non è disponibile la versione in italiano. Cosa ne pensi?

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +Questo codice aggiunge una condizione in entrambi gli event handlers e disabilita i pulsanti quando necessario:
```suggestion
Questo codice aggiunge una condizione in entrambi gli event handler e disabilita i pulsanti quando necessario:
```

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +Nota come `hasPrev` e `hasNext` vengono usati *sia* per il JSX ritornato che per gli event handlers! Questo comodo pattern funziona perché le funzioni event handlers ["chiudono sopra"](https://develo
```suggestion
Nota come `hasPrev` e `hasNext` vengono usati *sia* per il JSX ritornato che per gli event handler! Questo comodo pattern funziona perché le funzioni event handler ["chiudono sopra"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures) qualsiasi variabile dichiarata durante la renderizzazione.
```

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +Per prima cosa, importa `useState` da React. Poi sostituisci `firstName` e `lastName` con delle variabili state dichiarate chiamando `useState`. Infine, sostituisci ogni assegnazione come `firstName
```suggestion
Per prima cosa, importa `useState` da React. Poi sostituisci `firstName` e `lastName` con delle variabili state dichiarate chiamando `useState`. Infine, sostituisci ogni assegnazione come `firstName = ...` con `setFirstName(...)` e fai lo stesso per `lastName`. Non dimenticare di aggiornare anche `handleReset` in modo che il pulsante di reset funzioni.
```

2023-05-28 15:47 UTC, mattia-sanfilippo commented on src/content/learn/state-a-components-memory.md
> +Se il tuo liner è [configurato per React](/learn/editor-setup#linting), dovresti vedere un errore lint quando commetti uno sbaglio del genere.  Se non vedi un errore quando provi il codice difettoso
```suggestion
Se il tuo linter è [configurato per React](/learn/editor-setup#linting), dovresti vedere un errore lint quando commetti uno sbaglio del genere.  Se non vedi un errore quando provi il codice difettoso localmente, devi impostare un linter per il tuo progetto.
```

2023-05-29 04:38 UTC, oxcened commented on src/content/learn/state-a-components-memory.md
> +2. **Triggerare** React per renderizzare il componente con nuovi dati (re-renderizzazione).
Eh beh sì qua ho sbagliato ✋

2023-05-29 04:39 UTC, oxcened commented on src/content/learn/state-a-components-memory.md
> +Avrai notato che la chiamata `useState` non riceve alcuna informazione circa *quale* variabile di stato prendere come riferimento. Non viene passato alcun "identificatore" a `useState`, quindi come f
Eh sì non l'ho mai tradotto, ho regredito chissà per quale motivo 😅

2023-05-29 04:41 UTC, oxcened commented on src/content/learn/state-a-components-memory.md
> +Internamente, React mantiene un array di coppie di stato per ogni componente. Mantiene anche l'indice della coppia corrente, che viene impostato su `0` prima della renderizzazione. Ogni volta che chi
Ci sta assolutamente, sono d'accordo che dovrebbe coincidere con il titolo originale dell'articolo 👍

2023-05-29 04:43 UTC, oxcened commented on src/content/learn/state-a-components-memory.md
> +Se il tuo liner è [configurato per React](/learn/editor-setup#linting), dovresti vedere un errore lint quando commetti uno sbaglio del genere.  Se non vedi un errore quando provi il codice difettoso
Mea culpa, e dire che ricontrollo sempre 🥲 Ottimo occhio!

2023-05-29 04:44 UTC, oxcened commented
> Ciao @oxcened, grazie mille per aver contribuito 😄 Ho suggerito alcune piccolissime modifiche, fammi sapere cosa ne pensi! 🚀

Ciao @mattia-sanfilippo mi trovi d'accordo su tutto e ho applicato le modifiche suggerite. Ma figurati grazie a te 🚀

2023-05-29 06:49 UTC, mattia-sanfilippo approved these changes

2023-05-29 06:49 UTC, merged