Translate: State as a snapshot page
reactjs/it.react.dev pull request #440
Opened 2023-05-04 08:39 UTC by NeilChavez

Hi!
Here is my contribution :)

* Translation of page content.
* Translation of page title in sidebarLearn.json.

See https://github.com/reactjs/it.react.dev/issues/418

2023-05-28 15:03 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +title: Lo stato come un'istantanea
```suggestion
title: Lo State come un'Istantanea
```
Come da linee guida, non traduciamo alcuni termini come _state_

2023-05-28 15:04 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Le variabili di stato possono sembrare delle normali variabili JavaScript su cui è possibile leggere e scrivere. Tuttavia lo stato si comporta più come un'istantanea. Quando lo si assegna, non si mod
```suggestion
Le variabili di state possono sembrare delle normali variabili JavaScript su cui è possibile leggere e scrivere. Tuttavia lo state si comporta più come un'istantanea. Quando lo si assegna, non si modifica la variabile di state che si ha già, ma si innesca una nuova renderizzazione.
```

2023-05-28 15:04 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Come l'assegnazione dello stato innesca re-renderizzazioni
```suggestion
* Come l'assegnazione dello state innesca re-renderizzazioni
```

2023-05-28 15:05 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Come e quando viene aggiornato lo stato
```suggestion
* Come e quando viene aggiornato lo state
```

2023-05-28 15:05 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Perché lo stato non viene aggiornato immediatamente dopo averlo assegnato
```suggestion
* Perché lo state non viene aggiornato immediatamente dopo averlo assegnato
```

2023-05-28 15:05 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Come i gestori di eventi accedono ad un'"istantanea" dello stato
```suggestion
* Come i gestori di eventi accedono ad un'"istantanea" dello state
```

2023-05-28 15:06 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +## Come l'assegnazione dello stato innesca re-renderizzazioni {/*setting-state-triggers-renders*/}
```suggestion
## Come l'assegnazione dello state innesca renderizzazioni {/*setting-state-triggers-renders*/}
```

2023-05-28 15:07 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Si potrebbe pensare che l'interfaccia dell'utente cambi direttamente in risposta ad un evento dell'utente stesso, come un click. In React funziona in modo leggermente diverso da questo modello mental
```suggestion
Si potrebbe pensare che l'interfaccia dell'utente cambi direttamente in risposta ad un evento dell'utente stesso, come un click. In React funziona in modo leggermente diverso da questo modello mentale. Nella pagina precedente si è visto che quando [si assegna lo state si richiede una nuova re-renderizzazione](/learn/render-and-commit#step-1-trigger-a-render) da React. Questo significa che per far reagire l'interfaccia al evento, è necessario *aggiornare lo state*.
```

2023-05-28 15:07 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +In questo esempio, quando premi "Send", `setIsSent(true)` dice a React di re-renderizzare la UI.
```suggestion
In questo esempio, quando premi "send", `setIsSent(true)` dice a React di re-renderizzare la UI:
```

2023-05-28 15:08 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +2. `setIsSent(true)` assegnat `isSent` a `true` e mette in coda un nuovo render.
```suggestion
2. `setIsSent(true)` assegna `isSent` a `true` e mette in coda un nuovo render.
```

2023-05-28 15:09 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Esaminiamo più da vicino la relazione tra lo stato e il renderizzato.
```suggestion
Esaminiamo più da vicino la relazione tra lo state e il renderizzato.
```

2023-05-28 15:09 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +## La renderizzazione scatta un'istantanea nel tempo {/*la-renderizzazione-scatta-unistantanea-nel-tempo*/}
```suggestion
## La renderizzazione scatta un'istantanea nel tempo {/*rendering-takes-a-snapshot-in-time*/}
```
Attenzione: i link non vanno tradotti

2023-05-28 15:10 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +["Renderizzare"](/learn/render-and-commit#step-2-react-renders-your-components) significa che React chiama il componente, che è una funzione. Il JSX che restituisce tale funzione è una istantanea del
```suggestion
["Renderizzare"](/learn/render-and-commit#step-2-react-renders-your-components) significa che React chiama il componente, che è una funzione. Il JSX che restituisce tale funzione è come un'istantanea della UI nel tempo. Le props, i gestori di eventi e le variabili locali sono stati calcolati **utilizzando il suo state al momento della renderizzazione.**
```

2023-05-28 15:11 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +A differenza di una fotografia o di un fotogramma di un film, l'"istantanea" della UI che viene restituita è interattiva. Include la logica, come i gestori di eventi che specificano cosa succede in r
```suggestion
A differenza di una fotografia o di un fotogramma di un film, l'"istantanea" della UI che viene restituita è interattiva. Include la logica, come i gestori di eventi che specificano cosa succede in risposta agli input. React aggiorna lo schermo in base a questa istantanea e collega i gestori di eventi. Di conseguenza, la pressione di un pulsante attiverà il gestore di click dal tuo JSX.
```

2023-05-28 15:11 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +    <Illustration caption="Calcola la istantanea" src="/images/docs/illustrations/i_render2.png" />
```suggestion
    <Illustration caption="Calcola l'istantanea" src="/images/docs/illustrations/i_render2.png" />
```

2023-05-28 15:12 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Come memoria di un componente, lo stato non è come una normale variabile che scompare dopo che la tua funzione restituisce un valore. Lo stato "vive" nello stesso React--come se si trattasse di uno s
```suggestion
Come memoria di un componente, lo state non è come una normale variabile che scompare dopo che la tua funzione restituisce un valore. Lo state "vive" nello stesso React--come se si trattasse di uno scaffale!--fuori dalla tua funzione. Quando React chiama il tuo componente, fornisce un'istantanea della UI per quel particolare renderizzato. Il tuo componente restituisce un'istantanea della UI con un nuovo set di props e gestori di eventi nel suo JSX, tutti calcolati **usando i valori dello stato di quel renderizzato.**
```

2023-05-28 15:13 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +  <Illustration caption="React aggiorna il valore dello stato" src="/images/docs/illustrations/i_state-snapshot2.png" />
```suggestion
  <Illustration caption="React aggiorna il valore dello state" src="/images/docs/illustrations/i_state-snapshot2.png" />
```

2023-05-28 15:13 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +  <Illustration caption="React passa un'istantanea del valore dello stato al componente" src="/images/docs/illustrations/i_state-snapshot3.png" />
```suggestion
  <Illustration caption="React passa un'istantanea del valore dello state al componente" src="/images/docs/illustrations/i_state-snapshot3.png" />
```

2023-05-28 15:14 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Ecco qui un piccolo esperimento per mostrarti come questo funziona. In questo esempio, potresti aspettarti che, cliccando il bottone "+3", il contatore venga incrementato tre volte, perché viene rich
```suggestion
Ecco qui un piccolo esperimento per mostrarti come questo funziona. In questo esempio, potresti aspettarti che, cliccando il bottone "+3", il contatore venga incrementato tre volte, perché viene chiamato `setNumber(number + 1)` tre volte.
```

2023-05-28 15:14 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +**L'assegnazione dello stato cambia solo per il *prossimo* renderizzato.** Durante il primo renderizzato, `number` era `0`. È per questo che, nel gestore `onClick` di *quel renderizzato*, il valore d
```suggestion
**L'assegnazione dello state cambia solo per la *prossima* renderizzazione .** Durante la prima renderizzazione, `number` era `0`. È per questo che, nel gestore `onClick` di *quella renderizzazione*, il valore di `number` è ancora `0`  anche dopo che stato chiamato `setNumber(number + 1)`:
```

2023-05-28 15:15 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Anche se chiami `setNumber(number + 1)` tre volte, nel gestore di eventi di *questa renderizzazione* `number` è sempre `0`, quindi stai assegnando lo stato a `1` per tre volte. Questo è il motivo per
```suggestion
Anche se hai chiamato `setNumber(number + 1)` tre volte, nel gestore di eventi di *questa renderizzazione* `number` è sempre `0`, quindi stai assegnando lo state a `1` per tre volte. Questo è il motivo per cui, dopo che il tuo gestore di eventi ha finito, React ri-renderizza il componente con `number` uguale a `1` piuttosto che `3`.
```

2023-05-28 15:16 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Puoi anche visualizzarlo sostituendo mentalmente le variabili di stato con i loro valori nel tuo codice. Poiché il valore della variabile di stato `number` è `0` per *questo renderizzato*, il suo ges
```suggestion
Puoi anche visualizzarlo sostituendo mentalmente le variabili di state con i loro valori nel tuo codice. Poiché il valore della variabile di state `number` è `0` per *questa renderizzazione*, il suo gestore di eventi si presenta in questo modo:
```

2023-05-28 15:16 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Per il prossimo renderizzato, `number` sarà `1`, quindi il gestore del click di *quel prossimo renderizzato* avrà l'aspetto seguente:
```suggestion
Per la prossima renderizzazione, `number` sarà `1`, quindi il gestore del click di *quella prossima renderizzazione* avrà il seguente aspetto:
```

2023-05-28 15:17 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +## Lo stato nel tempo {/*state-over-time*/}
```suggestion
## Lo state nel tempo {/*state-over-time*/}
```

2023-05-28 15:17 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Se utilizzi  il metodo si sostituzione di prima, puoi intuire che l'alert mostra "0":
```suggestion
Se utilizzi  il metodo di sostituzione di prima, puoi intuire che l'alert mostra "0":
```

2023-05-28 15:18 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Ma cosa succede se imposti un timer per l'alert, in modo che si attivi _dopo_ che il componente ha re-renderizzato? Mostrerà "0" o "5"? Indovina!
```suggestion
Ma cosa succede se imposti un timer per l'alert, in modo che si attivi _dopo_ che il componente viene ri-renderizzato? Mostrerà "0" o "5"? Indovina!
```

2023-05-28 15:18 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Sorpreso? Se hai utilizzato il metodo di sostituzione, puoi vedere l'"istantanea" del valore dello stato passato all'alert.
```suggestion
Sorpreso? Se hai utilizzato il metodo di sostituzione, puoi vedere l'"istantanea" del valore dello state passato all'alert.
```

2023-05-28 15:18 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Il valore dello stato memorizzato in React potrebbe essere cambiato al momento in cui si esegue l'alert, ma questo è stato pianificato utilizzando un'istantanea dello stato nel momento in cui l'utent
```suggestion
Il valore dello state memorizzato in React potrebbe essere cambiato al momento in cui si esegue l'alert, ma questo è stato pianificato utilizzando un'istantanea dello state nel momento in cui l'utente ha interagito con esso!
```

2023-05-28 15:19 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +**Il valore di una variabile di stato non cambia mai all'interno di un renderizzamento,** anche se il codice del suo gestore di eventi è asincrono. Dentro l'`onClick` di *quel render*, il valore di `
```suggestion
**Il valore di una variabile di state non cambia mai all'interno di una renderizzazione,** anche se il codice del suo gestore di eventi è asincrono. Dentro l'`onClick` di *quella renderizzazione*, il valore di `number` continua a essere `0` anche dopo che `setNumber(number + 5)` è stato eseguito. Il suo valore è stato "fissato" quando React ha "scattato l'istantanea" della UI chiamando il tuo componente. 
```

2023-05-28 15:20 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Cosa ti aspetti che mostri l'alert? Mostrerà "You said Hello to Alice"? Oppure "You said Hello to Bob"? Fai una previsione basandoti su che ciò che hai imparato e dopo provalo:
```suggestion
Cosa ti aspetti che mostri l'`alert`? Mostrerà "You said Hello to Alice"? Oppure "You said Hello to Bob"? Fai una previsione basandoti su che ciò che hai imparato e dopo provalo:
```

2023-05-28 15:20 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +**React mantiene i valori di stato "fissi" all'interno dei gestori di eventi di un renderizzato.** Non c'è bisogno di preoccuparsi se lo stato è cambiato durante l'esecuzione del codice.
```suggestion
**React mantiene i valori di state "fissi" all'interno dei gestori di eventi di una renderizzazione.** Non c'è bisogno di preoccuparsi se lo state è cambiato durante l'esecuzione del codice.
```

2023-05-28 15:21 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Ma cosa succede se vuoi leggere lo stato più recente prima di una nuova renderizzazione? In questo caso, si dovrebbe utilizzare una [funzione di aggiornamento dello stato](/learn/queueing-a-series-of
```suggestion
Ma cosa succede se vuoi leggere lo state più recente prima di una nuova renderizzazione? In questo caso, si dovrebbe utilizzare una [funzione di aggiornamento dello state](/learn/queueing-a-series-of-state-updates), descritta pagina successiva!
```

2023-05-28 15:21 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* L'assegnazione dello stato richiede un nuovo renderizzamento.
```suggestion
* L'assegnazione dello state richiede una nuova renderizzazione.
```

2023-05-28 15:21 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* React memorizza lo stato al di fuori del tuo componente, come se fosse su uno scaffale.
```suggestion
* React memorizza lo state al di fuori del tuo componente, come se fosse su uno scaffale.
```

2023-05-28 15:21 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Quando chiami `useState`, React ti fornisce un'istantanea dello stato per quella renderizzazione.
```suggestion
* Quando chiami `useState`, React ti fornisce un'istantanea dello state per quella renderizzazione.
```

2023-05-28 15:22 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Le variabili e i gestori di eventi non "sopravvivono" ai re-renderizzamenti. Ongi renderizzamento ha i propri gestori di eventi.
```suggestion
* Le variabili e i gestori di eventi non "sopravvivono" alle ri-renderizzazioni. Ogni renderizzazione ha i propri gestori di eventi.
```

2023-05-28 15:22 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Ogni renderizzamento (e le funzioni al suo interno) "vedranno" sempre l'istantanea dello stato che React ha dato in *quel* renderizzamento.
```suggestion
* Ogni renderizzazione (e le funzioni al suo interno) "vedrà" sempre l'istantanea dello state che React ha dato in *quella* renderizzazione.
```

2023-05-28 15:23 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* Puoi sostituire mentalmente lo stato nei gestori di eventi, in modo simile a a come pensi nel JSX renderizzato.
```suggestion
* Puoi sostituire mentalmente lo state nei gestori di eventi, in modo simile a a come pensi nel JSX renderizzato. 
```

2023-05-28 15:23 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +* I gestori di eventi creati in passato hanno il valore di stato del renderizzato in cui sono stati creati
```suggestion
* I gestori di eventi creati in passato hanno il valore di state della renderizzazione in cui sono stati creati
```

2023-05-28 15:24 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Non fa differenza se lo imposti prima o dopo della chiamata `setWalk`. Il valore della renderizzazione di `walk` rimane fisso. La chiamata a `setWalk` lo modificherà solo per la prossima renderizzazi
```suggestion
Non fa differenza se lo imposti prima o dopo della chiamata `setWalk`. Il valore della renderizzazione di `walk` rimane fisso. La chiamata a `setWalk` lo modificherà solo per la prossima renderizzazione, ma non influenzerà il gestore di eventi della renderizzazione precedente.
```

2023-05-28 15:25 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Però ha senso se la leggi come: "Se il semaforo mostra 'Walk now', il messaggio dovrebbe dire 'Stop is next.'" La variabile `walk` dentro il tuo gestore di eventi corrisponde al valore  di walk della
```suggestion
Però ha senso se la leggi come: "Se il semaforo mostra 'Walk now', il messaggio dovrebbe dire 'Stop is next.'" La variabile `walk` dentro il tuo gestore di eventi corrisponde al valore  di `walk` della renderizzazione e non cambia.
```

2023-05-28 15:25 UTC, mattia-sanfilippo commented on src/content/learn/state-as-a-snapshot.md
> +Quindi, cliccando su "Change to Stop", si mette in coda un rendering con `walk` impostato su `false` e viene visualizzato "Stop is next".
```suggestion
Quindi, cliccando su "Change to Stop", si mette in coda una renderizzazione con `walk` impostato su `false` e viene visualizzato "Stop is next". 
```

2023-05-28 15:26 UTC, mattia-sanfilippo commented on src/sidebarLearn.json
> +          "title": "Lo stato come un'istantanea",
```suggestion
          "title": "Lo state come un'Istantanea",
```

2023-05-28 15:29 UTC, mattia-sanfilippo requested changes
Ciao @NeilChavez, grazie per il contributo! :)

Ho suggerito alcune modifiche da apportare, alcuni errori di ortografia e la modifica di `stato` in `state`, perché secondo le linee guida non va mai tradotto.

Fammi sapere cosa ne pensi. Grazie! 🚀

2023-05-29 15:07 UTC, NeilChavez commented
Ciao @mattia-sanfilippo!
 Sono d'accordo con le modifiche che hai suggerito. Le ho applicate. 👍
Grazie per esserti preso il tempo di fare la review.  🚀

2023-05-30 07:46 UTC, merged