add rendering list translation
reactjs/it.react.dev pull request #442
Opened 2023-05-09 16:20 UTC by SamuelePiazzesi

2023-05-28 16:05 UTC, mattia-sanfilippo requested changes
Ciao @SamuelePiazzesi 👋 
Grazie per il contributo e ottimo lavoro! 😄

Ho proposto alcune modifiche. Fammi sapere cosa ne pensi! 🚀

2023-05-28 16:05 UTC, mattia-sanfilippo commented on src/content/learn/rendering-lists.md
> +Crea una lista di ricette! Per ogni ricetta nell'array, visualizza il suo nome come `<h2>` e elenca i suoi ingredienti in un `<ul>`.
```suggestion
Crea una lista di ricette da questo array! Per ogni ricetta nell'array, visualizza il suo nome come `<h2>` e elenca i suoi ingredienti in un `<ul>`.
```

2023-05-28 16:05 UTC, mattia-sanfilippo commented on src/content/learn/rendering-lists.md
> +Qui abbiamo bisogno di due cicli `map` annidati.
```suggestion
Qui abbiamo bisogno di due chiamate a `map` annidate.
```

2023-05-28 16:05 UTC, mattia-sanfilippo commented on src/content/learn/rendering-lists.md
> +Ogni `recipe` nell'array ha già un campo `id`, quindi è quello che il ciclo esterno usa per il suo `key`. Non c'è nessun ID che potresti usare per ciclare sugli ingredienti. Tuttavia, è ragionevole s
```suggestion
Ogni `recipe` nell'array ha già un campo `id`, quindi è quello che il ciclo esterno usa per il suo `key`. Non c'è nessun ID che potresti usare per iterare sugli ingredienti. Tuttavia, è ragionevole supporre che lo stesso ingrediente non sarà elencato due volte all'interno della stessa ricetta, quindi il suo nome può servire come `key`. In alternativa, potresti cambiare la struttura dei dati per aggiungere gli ID, o usare l'indice come `key` (con il caveat che non puoi riordinare gli ingredienti in modo sicuro).
```

2023-05-28 16:05 UTC, mattia-sanfilippo commented on src/content/learn/rendering-lists.md
> +Questo componente `RecipeList` contiene due chiamate `map` annidate. Per semplificarlo, estrai un componente `Recipe` da esso che accetterà le props `id`, `name` e `ingredients`. Dove posizioneresti
```suggestion
Questo componente `RecipeList` contiene due chiamate `map` annidate. Per semplificarlo, estrai un componente `Recipe` da esso che accetterà le props `id`, `name` e `ingredients`. Dove posizioneresti la `key` esterna e perché?
```

2023-05-28 16:05 UTC, mattia-sanfilippo commented on src/content/learn/rendering-lists.md
> +Puoi copia-incollare il JSX dal ciclo esterno `map` in un nuovo componente `Recipe` e restituire quel JSX. Quindi puoi cambiare `recipe.name` in `name`, `recipe.id` in `id`, e così via, e passarli co
```suggestion
Puoi copia-incollare il JSX dal `map` esterno in un nuovo componente `Recipe` e restituire quel JSX. Quindi puoi cambiare `recipe.name` in `name`, `recipe.id` in `id`, e così via, e passarli come props al `Recipe`:
```

2023-05-28 16:05 UTC, mattia-sanfilippo commented on src/content/learn/rendering-lists.md
> +In alternativa, potresti renderizzare una collection di fragments che contengono `<hr />` e `<p>...</p>`. Tuttavia, la sintassi abbreviata `<>...</>` non supporta il passaggio di key, quindi dovresti
```suggestion
In alternativa, potresti renderizzare una collezione di fragments che contengono `<hr />` e `<p>...</p>`. Tuttavia, la sintassi abbreviata `<>...</>` non supporta il passaggio di key, quindi dovresti scrivere `<Fragment>` esplicitamente:
```

2023-05-29 08:29 UTC, SamuelePiazzesi commented
Ciao @mattia-sanfilippo , grazie per la review! Ho accettato le modifiche suggerite, mi sembravano tutte sensate 👍

2023-05-29 08:31 UTC, merged