translate importing-exporting-components
reactjs/it.react.dev pull request #444
Opened 2023-05-12 10:22 UTC by eliamaino-fp

Added translations for `importing-exporting-components`.

See https://github.com/reactjs/it.react.dev/issues/418

2023-05-29 09:09 UTC, mattia-sanfilippo requested changes
Ciao @eliamaino-fp 👋 
Ottimo lavoro e grazie mille per aver contribuito! 🚀 

Ho proposto due piccolissime modifiche, facci sapere cosa ne pensi! 😄

2023-05-29 09:09 UTC, mattia-sanfilippo commented on src/content/learn/importing-and-exporting-components.md
> +Ora `Gallery.js` contiene due esportazioni: una predefinita `Gallery` e una denominata `Profile`. `App.js` le importa entrambe. Provate a modificare `<Profile />` in `<Gallery />` e viceversa in ques
```suggestion
Ora `Gallery.js` contiene due esportazioni: una predefinita `Gallery` e una denominata `Profile`. `App.js` le importa entrambe. Prova a modificare `<Profile />` in `<Gallery />` e viceversa in questo esempio:
```
Parlerei in singolare come fatto da altre parti :) Cosa ne pensi?

2023-05-29 09:09 UTC, mattia-sanfilippo commented on src/content/learn/importing-and-exporting-components.md
> +Sposta il componente `Profile` nel proprio `Profile.js`, quindi modifica il componente `App` per renderizzare sia `<Profile />` che `<Galleriy />` uno dopo l'altro.
```suggestion
Sposta il componente `Profile` nel proprio `Profile.js`, quindi modifica il componente `App` per renderizzare sia `<Profile />` che `<Gallery />` uno dopo l'altro.
```

2023-05-31 09:14 UTC, eliamaino-fp commented
Ciao @mattia-sanfilippo, grazie per la review! Ho sistemato i due errori :)

2023-05-31 09:24 UTC, mattia-sanfilippo approved these changes
Grazie @eliamaino-fp! 🚀

2023-05-31 09:27 UTC, merged