docs: extracting state logic into a reducer
reactjs/it.react.dev pull request #480
Opened 2024-01-11 09:49 UTC by paolapog

Partially address #418 
Thank you for the PR! Contributors like you keep React awesome!

Translation of page content.
Translation of page title in sidebarLearn.json.
Translation of page title in useReducer.md

2024-02-17 17:55 UTC, mattia-sanfilippo commented on src/sidebarLearn.json
> +          "title": "Estrarre la logica dello State in un Reducer",
```suggestion
          "title": "Estrarre la Logica dello State in un Reducer",
```
Usiamo lo stesso stile della versione originale, per convenzione :)

2024-02-17 17:56 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js ContactList.js hidden
```suggestion
```js src/ContactList.js hidden
```

2024-02-17 17:56 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js MyReact.js active
```suggestion
```js src/MyReact.js active
```

2024-02-17 17:56 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js messengerReducer.js
```suggestion
```js src/messengerReducer.js
```

2024-02-17 17:56 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js App.js
```suggestion
```js src/App.js
```

2024-02-17 17:57 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js Chat.js hidden
```suggestion
```js src/Chat.js hidden
```

2024-02-17 18:21 UTC, mattia-sanfilippo requested changes
Ciao @paolapog 👋
Grazie per aver contribuito! 
Ho lasciato alcuni commenti. Fammi sapere cosa ne pensi!

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js messengerReducer.js
```suggestion
```js src/messengerReducer.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js App.js
```suggestion
```js src/App.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js Chat.js
```suggestion
```js src/Chat.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js ContactList.js
```suggestion
```js src/ContactList.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js messengerReducer.js
```suggestion
```js src/messengerReducer.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js App.js
```suggestion
```js src/App.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Con entrambe le soluzioni, è importante che tu **non** posizioni l'`alert` all'interno di un reducer. Il reducer dovrebbe essere una funzione pura - dovrebbe solo calcolare il prossimo state. Non dov
```suggestion
Con entrambe le soluzioni, è importante che tu **non** posizioni l'`alert` all'interno di un reducer. Il reducer dovrebbe essere una funzione pura - dovrebbe solo calcolare il prossimo state. Non dovrebbe "fare" nulla, compreso mostrare messaggi all'utente. Questo dovrebbe avvenire nel event handler. (Per aiutare a individuare errori come questo, React chiamerà i tuoi reducer più volte in modalità Strict. Questo è il motivo per cui, se inserisci un alert in un reducer, si attiva due volte.)
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js Chat.js active
```suggestion
```js src/Chat.js active
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js ContactList.js
```suggestion
```js src/ContactList.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js messengerReducer.js active
```suggestion
```js src/messengerReducer.js active
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js App.js
```suggestion
```js src/App.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js Chat.js active
```suggestion
```js src/Chat.js active
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js ContactList.js
```suggestion
```js src/ContactList.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js messengerReducer.js
```suggestion
```js src/messengerReducer.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js App.js
```suggestion
```js src/App.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Ci sono un paio di modi che potresti utilizzare nel "Send" button event handler. Un approccio è quello di mostrare un alert e poi eseguire il dispatch di una azione `edited_message` con un `message`
```suggestion
Ci sono un paio di modi che potresti utilizzare nell'event handler del pulsante "Send". Un approccio è quello di mostrare un alert e poi eseguire il dispatch di una azione `edited_message` con un `message` vuoto:
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js Chat.js active
```suggestion
```js src/Chat.js active
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js ContactList.js
```suggestion
```js src/ContactList.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js messengerReducer.js
```suggestion
```js src/messengerReducer.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +```js App.js
```suggestion
```js src/App.js
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +  1. Esegui il dispatch delle azioni dagli event handlers.
```suggestion
  1. Esegui il dispatch delle azioni dagli event handler.
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +con `useReducer` così:
```suggestion
Con `useReducer` così:
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +La funzione che passi al `reduce` è conosciuta come un "riduttore". Essa prende il _risultato fino a quel momento_ e l'_elemento corrente_, per poi restituire il _prossimo risultato._ I reducers di R
```suggestion
La funzione che passi al `reduce` è conosciuta come un "reducer". Essa prende il _risultato fino a quel momento_ e l'_elemento corrente_, per poi restituire il _prossimo risultato._ I reducer di React sono un esempio della stessa idea: essi prendono _lo state fino a quel momento_ e l'_azione_, restituendo poi lo _state successivo_. In questo modo, essi accumulano le azioni nel tempo all'interno dello state.
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Il codice sopra utilizza le istruzioni if/else, ma è una convenzione utilizzare le [istruzioni switch](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/switch) all'interno dei r
```suggestion
Il codice sopra utilizza le istruzioni if/else, ma è una convenzione utilizzare le [istruzioni switch](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/switch) all'interno dei reducer. Il risultato è lo stesso, ma le istruzioni switch possono essere più facili da leggere a colpo d'occhio.
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Qui c'è tutta la logica del set state migrata in una funzione reducer:
```suggestion
Qui c'è tutta la logica di impostazione dello state migrata in una funzione reducer:
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Per convenzione, è comune dare un `type` stringa che descriva cosa è accaduto e per passare altre informazioni aggiuntive agli altri campi. Il `type` è specifico ad un componente, dunque in questo es
```suggestion
Per convenzione, è comune dare un `type` stringa che descriva cosa è accaduto e per passare altre informazioni aggiuntive agli altri campi. Il `type` è specifico ad un componente, dunque in questo esempio sia `'added'` che `'added_task'` vanno bene. Scegli un nome che descriva cosa è accaduto!
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Gestire lo state con i reducer è leggermente diverso dall'utilizzare direttamente un setting state. Invece di dire a React "cosa fare" utilizzando setting state, specifichi "cosa lo user ha appena fa
```suggestion
Gestire lo state con i reducer è leggermente diverso dall'utilizzare direttamente un setting state. Invece di dire a React "cosa fare" utilizzando setting state, specifichi "cosa lo user ha appena fatto" utilizzando delle azioni di dispatching che provengono dai tuoi event handler. (Lo state che aggiorna la logica vive da un altra parte!) Quindi invece di "impostare `tasks`" tramite un event handler, stai utiilizzando un'azione di dispatching come "aggiungere/modificare/cancellare un task". Questo descrive molto di più l'intenzione dell'utente.
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +title: Estrarre la logica dello State in un Reducer
```suggestion
title: Estrarre la Logica dello State in un Reducer
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +I componenti con molti aggiornamenti di state distruibiti su molti event handler può diventare eccessivo. In questi casi, è possibile consolidare tutti gli aggiornamenti della logica dello state fuor
```suggestion

I componenti con molti aggiornamenti di state distruibiti su molti event handler può diventare eccessivo. In questi casi, è possibile consolidare tutti gli aggiornamenti della logica dello state fuori dal componente in una singola funzione, chiamata _reducer._
```

2024-02-17 18:21 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +I componenti con molti aggiornamenti di state distruibiti su molti event handler può diventare eccessivo. In questi casi, è possibile consolidare tutti gli aggiornamenti della logica dello state fuor
Teniamo lo stesso numero di linee rispetto all'originale :)

2024-02-18 13:52 UTC, paolapog commented
Ciao @mattia-sanfilippo , grazie per la review!
Credo di aver rebasato male da main ed è per questo che ho ancora i vecchi path sugli esercizi, try better next time :)

2024-02-18 14:05 UTC, mattia-sanfilippo requested changes

2024-02-18 14:05 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Lo `useReducer` Hook è simile allo `useState`-devi passargli uno stato iniziale e lui ti restituisce un valore dello stato e un modo per impostare lo stato (in questo caso, la funzione dispatch). Ma
```suggestion
L'Hook `useReducer` è simile allo `useState`-devi passargli uno stato iniziale e lui ti restituisce un valore dello stato e un modo per impostare lo stato (in questo caso, la funzione dispatch). Ma è un po' diverso.
```

2024-02-18 14:09 UTC, mattia-sanfilippo requested changes

2024-02-18 14:09 UTC, mattia-sanfilippo commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Questo perché le azioni inviate vengono messe in coda fino al prossimo rendering, [similmente alle funzioni di aggiornamento.](/learn/queueing-a-series-of-state-updates)
Alla fine del file c'è un mismatch di 4 righe (originale 2625, traduzione 2621), dovremmo cercare di tenere lo stesso numero di righe per evitare problemi durante le PR di sync

2024-02-19 09:35 UTC, mattia-sanfilippo approved these changes

2024-02-19 09:35 UTC, mattia-sanfilippo commented
Grazie @paolapog ! 🚀

2024-02-19 09:36 UTC, merged